input_text = input('what would like the cat to say? ')
input_length = len(input_text)
print('          {}'.format('_' * input_length))
print('        < {} >'.format(input_text))
print('          {}'.format('-' * input_length))
print('         /')
print('        /')
#print(' /\\_/\\ /')
print(r' /\_/\ /')
print('( o.o )')
print(' > ^ <')